### ISSUE TITLE
Implement query method

### ISSUE THREAD

**Issue by mekwall** [brettlangdon/node-dogapi#12]
Query is an undocumented api method that is explained here: https://gist.github.com/clofresh/a390cd2cc7509d0939f0

**Comment by brettlangdon** [comment]
sure, I am actually working on #10 right now, so will include this in there as well.

**Comment by brettlangdon** [comment]
@mekwall sorry I didn't update here, but version `1.0.0` of `dogapi` is released, and query is implemented there, let me know if there are any issues.
