### ISSUE TITLE
Metrics not being sent

### ISSUE THREAD

**Issue by Limess** [brettlangdon/node-dogapi#15]
Hello there,

I've noticed that since updating to 1.0.0 metrics aren't being sent correctly and I'm getting no response back in my callbacks, and no metrics are being posted.

E.G
```javascript
var dogapi = require('dogapi');
dogapi.initialize({
    api_key: this.config.keys.datadog.api,
    app_key: this.config.keys.datadog.app
  });
var metrics =  [{
        metric: 'loadTest.avg_response_time',
        points: [1431343811, 2834],
        tags: [ 'exampleTag:v1' ]
      },
      {
        metric: 'loadTest.avg_error_rate',
        points: [1431343811, 0],
        tags: [ 'exampleTag:v1' ]
      }];

dogapi.metric.send_all(metrics, function(err, res) {
    if (err) {
      return callback(new DataDogAPIError(err), res);
    }
    callback(false, res);
  });
```

I get an empty response back and no error (``{ response: '' }``). Comparitively If I use the REST endpoint: 

curl  -X POST -H "Content-type: application/json" \
-d "{"series": [{
    "metric": "loadTest.avg_response_time",
    "points": [[1431342268, 2834], [1431342268, 2833]],
    "tags": ["exampleTag:v1"]
}]}" 
'https://app.datadoghq.com/api/v1/series?api_key=DD_API_KEY'

using postman I get the response
```{
"status": "ok"
}```

**Comment by brettlangdon** [comment]
thanks for reporting @Limess, if you update to `v1.0.2` should be all good.

The problem was I was missing the `series` property:

**I was sending**
```json
[
  {
    "metric": "loadTest.avg_response_time",
    "points": [[1431342268, 2834], [1431342268, 2833]],
    "tags": ["exampleTag:v1"]
  }
]
```

**Should have been**
```json
{
  "series": 
    [
      {
        "metric": "loadTest.avg_response_time",
        "points": [[1431342268, 2834], [1431342268, 2833]],
        "tags": ["exampleTag:v1"]
      }
    ]
}
```
