### ISSUE TITLE
Event 'id' loss of precision due to JSON.parse

### ISSUE THREAD

**Issue by scottgunther** [brettlangdon/node-dogapi#16]
Here is the output before JSON.parse(data) on line #100 of lib/api/client.js

```
{"status": "ok",
  "event": 
    {  "priority": null,
       "date_happened": 1435260251,
       "handle": null, "title": "Nimbus Sanity Test",
       "url": "https://app.datadoghq.com/event/event?id=2868860079149422351",
       "text": "Sanity Test Datadog",
       "tags": null,
       "related_event_id": null,
       "id": 2868860079149422351 }
}
```

After parsing:

```
{ status: 'ok',
  event: 
   { priority: null,
     date_happened: 1435260251,
     handle: null,
     title: 'Nimbus Sanity Test',
     url: 'https://app.datadoghq.com/event/event?id=2868860079149422351',
     text: 'Sanity Test Datadog',
     tags: null,
     related_event_id: null,
     id: 2868860079149422600 }
 }
```

**Comment by brettlangdon** [comment]
```
> var data = '{"id": 2868860079149422351}';
undefined
> JSON.parse(data);
{ id: 2868860079149422600 }
>
```

Yup, well will you look at that. This is probably going to be a tricky one to fix, but I'll see what I can do to get around it.

Thanks for reporting @scottgunther

**Comment by brettlangdon** [comment]
Making note of it here for later: https://www.npmjs.com/package/json-bigint

**Comment by brettlangdon** [comment]
@scottgunther just published `v1.0.3`, give that a try and let me know if the problem still exists

**Comment by scottgunther** [comment]
works great. Thanks for the quick fix

**Comment by alleles** [comment]
Here is the output before returning data back to the callback on line #108 of lib/api/client.js

...
"pointlist":[[1438875830000,4],[1438875850000,4],[1438875870000,{"s":1,"e":0,"c":[3,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,5]}],[1438875890000,{"s":1,"e":0,"c":[9,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,9]}]
...

If I change json.stringify back to JSON.stringify and json.parse back to JSON.parse it looks like:

...
"pointlist":[[1438875830000,4],[1438875850000,4],[1438875870000,3.6666666666666665],[1438875890000,9.3333333333333339]
...

When I receive this data in my app it looks like it's been big-int-ified. I attempted to use the logical combinations of JSONBig.stringify / JSON.parse in my callback with no luck. I was able to get the code working by changing the return value to JSONBig.stringify in client.js and then use a JSON.parse in my callback code but that is a total hack.

**Comment by brettlangdon** [comment]
@alleles I am not sure I follow what the problem is. Can you provide some code examples from your callback and where the issues lie?

**Comment by alleles** [comment]
sure.. 

  var dogapi = require("dogapi");
  var options = {
    api_key: credentials.username,
    app_key: credentials.password
  };

  dogapi.initialize(options);
  var now = parseInt(new Date().getTime() / 1000);
  var then = now - 60 * 15; //15 mins ago
  var query = "system.cpu.idle{host:" + instance.id + "},system.load.1{host:" + instance.id + "},system.cpu.iowait{host:" + instance.id + "},system.cpu.user{host:" + instance.id + "},system.mem.cached{host:" + instance.id + "},system.mem.used{host:" + instance.id + "},system.mem.usable{host:" + instance.id + "},system.io.w_s{host:" + instance.id + "},system.io.r_s{host:" + instance.id + "}";

dogapi.metric.query(then, now, query, function(err, metrics, responseCode){
    console.log('code: ' + responseCode);
    console.log(metrics);
}

using 1.0.3 the pointlists that contain decimals look like this:

...
"pointlist":[[1438875830000,4],[1438875850000,4],[1438875870000,{"s":1,"e":0,"c":[3,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,5]}],[1438875890000,{"s":1,"e":0,"c":[9,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,9]}]
...

when running with 1.0.2 it looks like this:

...
"pointlist":[[1438875830000,4],[1438875850000,4],[1438875870000,3.6666666666666665],[1438875890000,9.3333333333333339]
...

**Comment by brettlangdon** [comment]
Ok, so the problem is that `json-bigint` is converting any number that is longer than 15 characters in length to a `BigNumber`. Rather than numbers which fall outside of the min/max number range. https://github.com/sidorares/json-bigint/blob/919bdb9085dc209d20f5dc38c005079ff39e6db8/lib/parse.js#L170-L174

This then gets complicated with decimals, since the number of decimal places a number can have is based on how large the number to the left of the decimal is:

```
> 3.6666666666666665
3.6666666666666665
> 43.6666666666666665
43.666666666666664
> 543.6666666666666665
543.6666666666666
> 2323929543.6666666666666665
2323929543.6666665
```

I have been going back and forth trying to find a good way to solve the problem and I don't think there is one. This library needs support for numbers larger than `Number.MAX_VALUE`, so unfortunately we have to keep `json-bigint`.

I am going to open a ticket for `json-bigint` outlining this issue we are seeing.
