### ISSUE TITLE
`tags` is not defined when sending metrics

### ISSUE THREAD

**Issue by chrisjhoughton** [brettlangdon/node-dogapi#18]
On this line https://github.com/brettlangdon/node-dogapi/blob/master/lib/api/metric.js#L38, I'm assuming you should be setting callback as `extra`, not `tags`, right? `tags` is undefined.

**Comment by brettlangdon** [comment]
Hey @chrisjhoughton, yup, that definitely looks like the issue. I'll see if I can get to it sometime today, thanks for catching.

**Comment by brettlangdon** [comment]
@chrisjhoughton just released version `1.0.4` which should resolve this issue, let me know if it doesn't.
