### ISSUE TITLE
Update Screenboard API

### ISSUE THREAD

**Issue by lewisf** [brettlangdon/node-dogapi#45]
Screenboard API's create api in the library currently indicates that a 'graph' key should be passed in.

However http://docs.datadoghq.com/api/screenboards/ doesn't make a mention of the `graph` key.

Additionally it looks like the `update` method isn't supported on the Screenboard API though it shouldn't be hard to add.

I'm happy to open a pull request to add it if you're okay with it @brettlangdon

**Comment by brettlangdon** [comment]
hmm, yeah, looks like they changed their API on us. Looks like they accept a `widgets` property instead of `graphs` now.

@lewisf more than happy to accept a PR for this. otherwise, not sure I'd have the time to address right away (maybe by the end of the week...).

**Comment by brettlangdon** [comment]
\0/

**Comment by brettlangdon** [comment]
This was resolved by @lewisf in #48
