### ISSUE TITLE
XMLHttpRequest cannot load

### ISSUE THREAD

**Issue by frioles** [brettlangdon/node-dogapi#47]
Not sure if this is related to the api or my node setup, but I'm getting
```
XMLHttpRequest cannot load <link>. 
No 'Access-Control-Allow-Origin' header is present on the requested resource.
Origin 'http://localhost:8080' is therefore not allowed access.
```

I've added this to my app already:
``` javascript
app.use(function (req, res, next) {
  // Website you wish to allow to connect
  res.setHeader('Access-Control-Allow-Origin', 'http://localhost:8080');

  // Request methods you wish to allow
  res.setHeader('Access-Control-Allow-Methods', 'GET, POST, OPTIONS, PUT, PATCH, DELETE');

  // Request headers you wish to allow
  res.setHeader('Access-Control-Allow-Headers', 'X-Requested-With,content-type');

  // Set to true if you need the website to include cookies in the requests sent
  // to the API (e.g. in case you use sessions)
  res.setHeader('Access-Control-Allow-Credentials', true);

  // Pass to next layer of middleware
  next();
});
```

I also tried running it through a proxy like in the example-
```javascript
agent = new HttpsProxyAgent({
   proxyHost: "localhost",
   proxyPort: 8080
  });
```
but then I get
`Error: (SystemJS) Node tls module not supported in browsers.`

I think that may be a separate issue as I used JSPM to install https-proxy-agent for an angularjs app.

But overall how would I get it set up to not have the XMLHttpRequest error?

**Comment by frioles** [comment]
solved - make POST to Express middleware, then make the datadog calls in the handlers and pass back to Angular

**Comment by brettlangdon** [comment]
@frioles sorry I was AFK all day and couldn't respond. I am glad you were able to figure it out!
