### ISSUE TITLE
share function in screenboard.js doesn't share the given board 

### ISSUE THREAD

**Issue by mahhafez** [brettlangdon/node-dogapi#60]
in Screenboard.js the function share is not using the correct http method it should be "POST" instead of "GET"
as the current behavior wont actually share the given screen-board 
function share(boardId, callback){
    client.request("GET", util.format("/screen/share/%s", boardId), callback);
} 
it should be 
function share(boardId, callback){
    client.request("POST", util.format("/screen/share/%s", boardId), callback);
}

**Comment by brettlangdon** [comment]
Merged and released #57 under version `2.8.3`.
