### ISSUE TITLE
Add support for new "downtime" API calls

### ISSUE THREAD

**Issue by VynceMontgomery** [brettlangdon/node-dogapi#9]
per http://docs.datadoghq.com/api/#schedule-downtime

.

**Comment by brettlangdon** [comment]
Not sure I'll have the time today, but I'll see if I can get to it this week.

**Comment by brettlangdon** [comment]
hey @VynceMontgomery should be good to go, `v0.2.0` is now published on npm. let me know if you have any issues with any of it.

**Comment by VynceMontgomery** [comment]
beautiful, thanks.
